-- ============================================================
-- TNC Recruitment Portal — Seed Data
-- Run AFTER schema.sql
-- Default password (plain): password  ← CHANGE BEFORE GO-LIVE
-- ============================================================

USE tnc_recruitment;

INSERT INTO users (username, email, password_hash, role, full_name) VALUES
('superadmin',  'admin@transnzoia.go.ke',       '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uQF8n5ZrC', 'superadmin', 'System Administrator'),
('hr_officer',  'hr@transnzoia.go.ke',          '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uQF8n5ZrC', 'hr',         'HR Officer'),
('recruitment', 'recruitment@transnzoia.go.ke', '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uQF8n5ZrC', 'admin',      'Recruitment Officer');

-- County-wide jobs
INSERT INTO jobs (job_code,title,department,type,deadline,posted_date,status,vacancies,min_experience,salary_scale,scope,description,requirements,responsibilities,created_by) VALUES
('TNC/PO/2026','Procurement Officer','Finance & Procurement','Full-Time','2026-02-28','2025-12-01','Closed',1,3,'Job Group L','county_wide','Manage procurement of goods, services and works in compliance with PPADA 2015.',"Bachelor's Degree in Procurement/Supply Chain Management\nMinimum 3 years relevant experience\nValid KISM membership\nComputer proficiency","Prepare and implement annual procurement plans\nManage tendering process\nMaintain supplier records\nEnsure PPADA 2015 compliance",1),
('TNC/ICT/2026','ICT Officer','ICT Department','Full-Time','2026-03-31','2026-03-01','Open',1,2,'Job Group K','county_wide','Support county ICT infrastructure, systems administration, network management and digital services.',"Bachelor's Degree in ICT or Computer Science\nMinimum 2 years experience\nCCNA preferred","Administer county servers and networks\nProvide technical support\nMaintain county digital platforms\nEnsure data security",1),
('TNC/FIN/2026','Finance Officer','Finance & Accounts','Full-Time','2026-03-31','2026-03-01','Open',2,3,'Job Group L','county_wide','Support financial management, budgeting, accounting and reporting per the PFM Act 2012.',"Bachelor's Degree in Finance or Accounting\nCPA(K) or ACCA\nMinimum 3 years experience\nIFMIS knowledge","Prepare financial statements\nManage budget implementation\nProcess payments\nCoordinate audits",1),
('TNC/HR/2026','Human Resource Officer','Public Service Management','Full-Time','2026-04-15','2026-03-10','Open',1,3,'Job Group L','county_wide','Manage county human resource functions including recruitment, welfare and performance management.',"Bachelor's Degree in Human Resource Management\nHigher Diploma in HRM\nMinimum 3 years experience\nIHRM membership","Coordinate recruitment processes\nMaintain personnel records\nImplement performance appraisal\nHandle staff welfare",1),
('TNC/LGL/2026','Legal Officer','County Attorney Office','Full-Time','2026-04-15','2026-03-10','Open',1,4,'Job Group M','county_wide','Provide legal advice and representation to the County Government on all legal matters.',"LLB Degree\nAdvocate of the High Court of Kenya\nMinimum 4 years post-admission experience\nLSK membership","Draft and review contracts\nRepresent county in legal proceedings\nAdvise on legal compliance\nPrepare legal opinions",1),
('TNC/AGR/2026','Agricultural Officer','Agriculture & Livestock','Full-Time','2026-04-30','2026-03-15','Open',3,2,'Job Group K','county_wide','Promote agricultural development and provide extension services across Trans Nzoia County.',"Bachelor's Degree in Agriculture\nMinimum 2 years experience\nProfessional registration","Provide agricultural extension services\nCoordinate development programmes\nConduct farmer training\nPrepare agricultural reports",1);

-- Ward-specific: Community Health Promoters (one per ward, 24 total)
-- Cherangany
INSERT INTO jobs (job_code,title,department,type,deadline,posted_date,status,vacancies,min_experience,salary_scale,scope,target_sub_county,target_ward,description,requirements,responsibilities,created_by) VALUES
('TNC/CHP/CHE/SNY','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Cherangany','Sinyereri','Community health promotion and disease prevention in Sinyereri Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Sinyereri Ward","Household health visits\nCommunity health records\nHealth education sessions\nDisease outbreak reporting",1),
('TNC/CHP/CHE/KAP','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Cherangany','Kaplamai','Community health promotion and disease prevention in Kaplamai Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Kaplamai Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/CHE/MOT','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Cherangany','Motosiet','Community health promotion in Motosiet Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Motosiet Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/CHE/CHK','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Cherangany','Chepsiro/Kiptoror','Community health promotion in Chepsiro/Kiptoror Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Chepsiro/Kiptoror Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/CHE/MAK','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Cherangany','Makutano','Community health promotion in Makutano Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Makutano Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/CHE/CSU','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Cherangany','Cherangany/Suwerwa','Community health promotion in Cherangany/Suwerwa Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Cherangany/Suwerwa Ward","Household health visits\nCommunity health records\nHealth education sessions",1);

-- Kwanza
INSERT INTO jobs (job_code,title,department,type,deadline,posted_date,status,vacancies,min_experience,salary_scale,scope,target_sub_county,target_ward,description,requirements,responsibilities,created_by) VALUES
('TNC/CHP/KWA/KWA','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kwanza','Kwanza','Community health promotion in Kwanza Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Kwanza Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/KWA/KEI','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kwanza','Keiyo','Community health promotion in Keiyo Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Keiyo Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/KWA/KAP','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kwanza','Kapomboi','Community health promotion in Kapomboi Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Kapomboi Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/KWA/BID','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kwanza','Bidii','Community health promotion in Bidii Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Bidii Ward","Household health visits\nCommunity health records\nHealth education sessions",1);

-- Saboti
INSERT INTO jobs (job_code,title,department,type,deadline,posted_date,status,vacancies,min_experience,salary_scale,scope,target_sub_county,target_ward,description,requirements,responsibilities,created_by) VALUES
('TNC/CHP/SAB/MAC','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Saboti','Machewa','Community health promotion in Machewa Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Machewa Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/SAB/KIN','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Saboti','Kinyoro','Community health promotion in Kinyoro Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Kinyoro Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/SAB/SAB','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Saboti','Saboti','Community health promotion in Saboti Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Saboti Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/SAB/MAT','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Saboti','Matisi','Community health promotion in Matisi Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Matisi Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/SAB/TUW','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Saboti','Tuwan','Community health promotion in Tuwan Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Tuwan Ward","Household health visits\nCommunity health records\nHealth education sessions",1);

-- Endebess
INSERT INTO jobs (job_code,title,department,type,deadline,posted_date,status,vacancies,min_experience,salary_scale,scope,target_sub_county,target_ward,description,requirements,responsibilities,created_by) VALUES
('TNC/CHP/END/END','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Endebess','Endebess','Community health promotion in Endebess Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Endebess Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/END/MAT','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Endebess','Matumbei','Community health promotion in Matumbei Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Matumbei Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/END/CHE','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Endebess','Chepchoina','Community health promotion in Chepchoina Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Chepchoina Ward","Household health visits\nCommunity health records\nHealth education sessions",1);

-- Kiminini
INSERT INTO jobs (job_code,title,department,type,deadline,posted_date,status,vacancies,min_experience,salary_scale,scope,target_sub_county,target_ward,description,requirements,responsibilities,created_by) VALUES
('TNC/CHP/KIM/SIK','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kiminini','Sikhendu','Community health promotion in Sikhendu Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Sikhendu Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/KIM/NAB','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kiminini','Nabiswa','Community health promotion in Nabiswa Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Nabiswa Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/KIM/SIR','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kiminini','Sirende','Community health promotion in Sirende Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Sirende Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/KIM/WAI','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kiminini','Waitaluk','Community health promotion in Waitaluk Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Waitaluk Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/KIM/HOS','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kiminini','Hospital','Community health promotion in Hospital Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Hospital Ward","Household health visits\nCommunity health records\nHealth education sessions",1),
('TNC/CHP/KIM/KIM','Community Health Promoter','Health Services','Full-Time','2026-04-30','2026-03-15','Open',1,0,'Job Group D','ward_specific','Kiminini','Kiminini','Community health promotion in Kiminini Ward.',"KCSE C- minimum\nCertificate in Community Health\nResident of Kiminini Ward","Household health visits\nCommunity health records\nHealth education sessions",1);

-- Applications
INSERT INTO applications (ref_no,job_id,first_name,last_name,id_no,dob,gender,phone,email,degree,institution,kism_no,experience,sub_county,ward,status,submitted_at) VALUES
('APP-001',1,'Pammelor Machuma','Lukorito',  '—',        '1979-09-30','Female','07231335795',     '—',                          'B.Sc Purchasing & Supply Management','Nairobi TTI',        'K3622/2023','18 Years','Saboti',    'Matisi',    'Shortlisted',    '2025-12-15'),
('APP-002',1,'Simiyu Everlyne', 'Nanjala',   '26728687', '1987-04-30','Female','0710480419',      'everlynesimiyu308@gmail.com', 'BCom Procurement & SCM',             'Gretsa University',  'P21-5270',  '15 Years','Kwanza',    'Bidii',     'Shortlisted',    '2025-12-19'),
('APP-003',1,'Namwetako N',     'Branice',   '23396146', '1993-07-07','Female','0725813840',      'naliakabranice@gmail.com',    'BCom Procurement & SCM',             'KIM',                '—',         '7 Years', 'Cherangany','Makutano',  'Shortlisted',    '2025-12-10'),
('APP-004',1,'Maiyo J',         'Felicity',  '29741101', '1993-05-23','Male',  '0723619676',      'felikirui@gmail.com',         'BSc Procurement & Contract Mgmt',    'Moi University',     'K4731/2024','6 Years', 'Endebess',  'Chepchoina','Shortlisted',    '2025-12-19'),
('APP-005',1,'Losyel L',        'James',     '27699820', '1989-01-01','Male',  '0720688676',      'losjamie46@gmail.com',        'MSc Procurement & Logistics',        'JKUAT',              '—',         '5 Years', 'Kiminini',  'Kiminini',  'Shortlisted',    '2025-12-19'),
('APP-006',1,'Isaac Wabukhe',   'Barasa',    '30433337', '1993-08-23','Male',  '0718785620',      'isaacbarasa64@gmail.com',     'BCom Purchasing & SCM',              'Kibabii University', '080271',    '4 Years', 'Saboti',    'Kinyoro',   'Shortlisted',    '2025-12-18'),
('APP-007',1,'Ngeno Kibet',     'Japheth',   '28656187', '1991-11-28','Male',  '072985410',       'kibetjapheth7@gmail.com',     'BSc Procurement & Contract Mgmt',    'JKUAT',              '80253',     '4 Years', 'Cherangany','Sinyereri', 'Shortlisted',    '2025-12-17'),
('APP-008',1,'Mwandike Mercy',  'Chebukati', '31537786', '1994-12-10','Female','0702897863',      'mercychebukati@gmail.com',    'B.Sc Purchasing & Supplies',         'Univ of Eldoret',    '003298',    '—',       'Kwanza',    'Keiyo',     'Not Shortlisted','2025-12-01'),
('APP-009',1,'Ogola O',         'Dennis',    '26789547', '1987-05-25','Male',  '0705446010',      'dennisogola@gmail.com',       'BCom',                               'Univ of Nairobi',    '—',         '—',       'Saboti',    'Machewa',   'Not Shortlisted','2025-12-02'),
('APP-010',1,'Gloria Lutasa',   'Murunga',   '26649081', '1988-11-17','Female','0722230269',      'glomurunga88@gmail.com',      'BCom Procurement',                   'Mama Ngina Univ',    '75153',     '1 Year',  'Endebess',  'Endebess',  'Not Shortlisted','2025-12-03');
